FROM rust:alpine as builder

WORKDIR /app
RUN USER=root

RUN apk add --no-cache pkgconfig build-base musl-dev libressl-dev
COPY ./ ./
RUN cargo build --release

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/target/release/{{project_name}}  /app/{{project_name}}
ENTRYPOINT ["/app/{{project_name}}"]
CMD ["start"]