FROM lukemathwalker/cargo-chef:latest-rust-1-alpine3.21 AS chef
WORKDIR /app
RUN apk add --no-cache upx

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

{% if frontend!='none' -%}
FROM node:24-slim AS node
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY ./frontend /app
ENV CI=true
WORKDIR /app
RUN pnpm install
RUN pnpm build
{% endif %}

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .

{% if protocol=='grpc' -%}
RUN apk add --no-cache protobuf-dev protoc
{% endif -%}

{% if frontend!='none' -%}
COPY --from=node /app/dist /app/frontend/dist
{% endif %}
RUN cargo test
RUN cargo build --release
RUN upx --best --lzma /app/target/release/{{project_name}}

FROM dhi.io/static:20250419 AS runtime
COPY --from=builder /app/target/release/{{project_name}} /

EXPOSE 8080

ENTRYPOINT ["/{{project_name}}"]