FROM rust:alpine as builder

WORKDIR /app
RUN USER=root

RUN apk add --no-cache pkgconfig build-base musl-dev libressl-dev
COPY ./ ./
RUN cargo build --release

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/target/release/{{project_name}}  /app/{{project_name}}
COPY --from=builder /app/config /app/config
{% if frontend_framework != 'none' -%}
COPY --from=node /app/dist /app/static
{% endif %}
ENTRYPOINT ["/app/{{project_name}}"]
CMD ["start"]